before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    main: ./cmd
    binary: gbox
    ldflags:
      - -X 'github.com/zezaeoh/gbox/internal/common.Version={{ .Version }}'
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "README"
      - Merge pull request
      - Merge branch
brews:
  - name: gbox
    goarm: 6
    tap:
      owner: zezaeoh
      name: homebrew-gbox
    commit_author:
      name: zezaeoh
      email: zezaeoh@gmail.com
    folder: Formula
    homepage: https://github.com/zezaeoh/gbox
    description: Gbox - use github as storage
    license: "MIT"
    install: |
      bin.install "gbox"
      
      # Install bash completion
      output = Utils.popen_read("#{bin}/gbox completion bash")
      (bash_completion/"gbox").write output
      
      # Install zsh completion
      output = Utils.popen_read("#{bin}/gbox completion zsh")
      (zsh_completion/"_gbox").write output
    test: |
      system "gbox version"