name: Check code coverage

on: [push, pull_request]
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          go mod download
      - name: Run Unit tests
        run: |
          go test -v -coverprofile=profile.cov ./...
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
